pipelines:
  default:
      - step:
          image: elixir:latest
          name: Latest Elixir
          script:
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - mix test
      - step:
          image: elixir:1.8-alpine
          name: Elixir 1.8
          script:
          - apk add --no-cache openssl openssh-client
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - mix test
      - step:
          image: elixir:1.7-alpine
          name: Elixir 1.7
          script:
          - apk add --no-cache openssl openssh-client
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - mix test
      - step:
          image: elixir:1.6-alpine
          name: Elixir 1.6
          script:
          - apk add --no-cache openssl openssh-client
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - mix test
      - step:
          image: elixir:1.5-alpine
          name: Elixir 1.5
          script:
          - apk add --no-cache openssl openssh-client
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - mix test
      - step:
          image: elixir:1.4.4-slim
          name: Elixir 1.4
          script:
          - apt-get update && apt-get install -y openssl openssh-client
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - mix test
